#!/usr/bin/env -S npx tsx

import { createHash } from 'node:crypto';
import { readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import process from 'node:process';
import { fileURLToPath } from 'node:url';

const POLICY_BEGIN = '<!-- AGENT_POLICY:BEGIN -->';
const POLICY_END = '<!-- AGENT_POLICY:END -->';

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(scriptDir, '..', '..');
const canonicalPath = path.join(repoRoot, 'AGENTS.md');
const generatedPath = path.join(repoRoot, 'dev-docs', 'AGENTS.md');

const quickUsage = [
  '## Quick Usage',
  '',
  '- Refresh docs: `make fetch-docs` (or `./dev-docs/fetch-docs.sh`).',
  '- Add/update sources: edit `dev-docs/packages.yaml`, then re-run fetch.',
  '- Commit regenerated `dev-docs/*/llms.txt` files so CI stays in sync.',
  '',
  'See `dev-docs/README.md` for details and grep helpers.',
];

function readPolicyBlock(content: string): string {
  const start = content.indexOf(POLICY_BEGIN);
  if (start < 0) {
    throw new Error(`Missing policy begin marker in ${canonicalPath}`);
  }

  const from = start + POLICY_BEGIN.length;
  const end = content.indexOf(POLICY_END, from);
  if (end < 0) {
    throw new Error(`Missing policy end marker in ${canonicalPath}`);
  }

  return content.slice(from, end).trim();
}

function sha256(value: string): string {
  return createHash('sha256').update(value, 'utf8').digest('hex');
}

function renderGeneratedFile(policyBlock: string): string {
  const hash = sha256(policyBlock);
  return [
    '# Dev Docs Usage',
    '',
    '> Auto-generated from `AGENTS.md`. Run `make sync-agent-policy` to regenerate.',
    '> Do not edit this file directly. Run `make sync-agent-policy`.',
    `> Policy SHA256: \`${hash}\``,
    '',
    '## Canonical Agent Governance Policy',
    '',
    policyBlock,
    '',
    ...quickUsage,
    '',
  ].join('\n');
}

async function run(): Promise<void> {
  const checkMode = process.argv.includes('--check');
  const canonicalContent = await readFile(canonicalPath, 'utf8');
  const policyBlock = readPolicyBlock(canonicalContent);
  const expected = renderGeneratedFile(policyBlock);

  if (checkMode) {
    const current = await readFile(generatedPath, 'utf8');
    if (current !== expected) {
      console.error('Policy mirror drift detected in dev-docs/AGENTS.md');
      console.error('Run: make sync-agent-policy');
      process.exit(1);
    }
    console.log('Policy mirror is up to date');
    return;
  }

  await writeFile(generatedPath, expected, 'utf8');
  console.log(`Generated ${generatedPath}`);
}

run().catch((error: unknown) => {
  console.error('Failed to sync agent policy:', error);
  process.exit(1);
});
