/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health check
         * @description Returns the health status of the API
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Service is healthy */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HealthResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trends": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get trending news
         * @description Returns the latest trending news items from various platforms
         */
        get: {
            parameters: {
                query?: {
                    platform?: string;
                    date?: string;
                    limit?: string;
                    include_url?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successful response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TrendsResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trends/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get trend details
         * @description Returns detailed information about a specific trend item
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successful response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TrendDetailResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/topics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get trending topics
         * @description Returns aggregated trending topics based on keyword frequency
         */
        get: {
            parameters: {
                query?: {
                    top_n?: string;
                    mode?: "daily" | "current";
                    extract_mode?: "keywords" | "auto_extract";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successful response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TopicsResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search news
         * @description Search news items by keyword across platforms and dates
         */
        get: {
            parameters: {
                query: {
                    q: string;
                    platform?: string;
                    start_date?: string;
                    end_date?: string;
                    limit?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Search results */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SearchResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rss": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get RSS feed items
         * @description Returns the latest RSS feed items
         */
        get: {
            parameters: {
                query?: {
                    feed?: string;
                    days?: string;
                    limit?: string;
                    include_summary?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description RSS items */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RssResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/resumes/samples": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List resume sample files
         * @description Returns available resume sample JSON files stored under output/resumes/samples
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successful response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ResumeSamplesResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/resumes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List resumes from a sample file
         * @description Returns resume items from the latest or specified sample JSON
         */
        get: {
            parameters: {
                query?: {
                    sample?: string;
                    q?: string;
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successful response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ResumesResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthResponse: {
            /**
             * @example healthy
             * @enum {string}
             */
            status: "healthy" | "degraded" | "unhealthy";
            /** @example 2025-01-27T10:00:00Z */
            timestamp: string;
            /** @example 0.1.0 */
            version?: string;
        };
        TrendItem: {
            /** @example OpenAI announces GPT-5 */
            title: string;
            /** @example zhihu */
            platform: string;
            /** @example Zhihu Hot List */
            platform_name: string;
            /** @example 1 */
            rank: number;
            /** @example 2.5 */
            avg_rank?: number;
            /** @example 5 */
            count?: number;
            timestamp?: string;
            date?: string;
            url?: string;
            mobileUrl?: string;
        };
        TrendsResponse: {
            /** @enum {boolean} */
            success: true;
            summary?: {
                description: string;
                total: number;
                returned: number;
                platforms: string | string[];
            };
            data: components["schemas"]["TrendItem"][];
        };
        TrendDetailResponse: {
            /** @enum {boolean} */
            success: true;
            data: components["schemas"]["TrendItem"];
        };
        Topic: {
            /** @example AI */
            keyword: string;
            /** @example 15 */
            frequency: number;
            matched_news?: number;
            /** @enum {string} */
            trend?: "rising" | "stable" | "falling";
            weight_score?: number;
        };
        TopicsResponse: {
            /** @enum {boolean} */
            success: true;
            topics: components["schemas"]["Topic"][];
            generated_at?: string;
            mode?: string;
            extract_mode?: string;
            total_keywords?: number;
            description?: string;
        };
        SearchResult: {
            title: string;
            platform: string;
            platform_name: string;
            ranks?: number[];
            count?: number;
            avg_rank?: number;
            url?: string;
            mobileUrl?: string;
            date?: string;
        };
        SearchResponse: {
            /** @enum {boolean} */
            success: true;
            results: components["schemas"]["SearchResult"][];
            total: number;
            total_found?: number;
            statistics?: {
                platform_distribution?: {
                    [key: string]: number;
                };
                avg_rank?: number;
                keyword: string;
            };
        };
        RssItem: {
            title: string;
            feed_id: string;
            feed_name: string;
            url?: string;
            published_at?: string;
            author?: string;
            date?: string;
            fetch_time?: string;
            summary?: string;
        };
        RssResponse: {
            /** @enum {boolean} */
            success: true;
            summary?: {
                description: string;
                total: number;
                returned: number;
                days: number;
                feeds: string | string[];
            };
            data: components["schemas"]["RssItem"][];
        };
        ResumeSample: {
            /** @example sample-initial */
            name: string;
            /** @example sample-initial.json */
            filename: string;
            /** @example 2026-02-03T10:00:00.000Z */
            updatedAt: string;
            /** @example 10240 */
            size: number;
        };
        ResumeSamplesResponse: {
            /** @enum {boolean} */
            success: true;
            samples: components["schemas"]["ResumeSample"][];
        };
        ResumeSearchCriteria: {
            /** @example 销售 */
            keyword?: string;
            /** @example 东莞 */
            location?: string;
            /**
             * @example {
             *       "status": "active"
             *     }
             */
            filters?: {
                [key: string]: string;
            };
        };
        ResumeMetadata: {
            /** @example https://hr.job5156.com/search?keyword=销售 */
            sourceUrl?: string;
            searchCriteria?: components["schemas"]["ResumeSearchCriteria"];
            /** @example 2026-02-03T09:27:52.152Z */
            generatedAt?: string;
            /** @example browser-extension@1.0.0 */
            generatedBy?: string;
            /** @example 1 */
            totalPages?: number;
            /** @example 20 */
            totalResumes?: number;
            /** @example Navigate to sourceUrl, then add ?tr_auto_export=json */
            reproduction?: string;
        };
        ResumeWorkHistory: {
            /** @example 2021-03 ~ 2023-08 Example Co. - Sales Manager */
            raw: string;
        };
        ResumeItem: {
            /** @example Alex Chen */
            name: string;
            /** @example https://hr.job5156.com/resume/123 */
            profileUrl: string;
            /** @example Active today */
            activityStatus: string;
            /** @example 28 */
            age: string;
            /** @example 5 years */
            experience: string;
            /** @example Bachelor */
            education: string;
            /** @example Shenzhen */
            location: string;
            /** @example 认真敬业，具备团队协作精神 */
            selfIntro: string;
            /** @example Sales Manager */
            jobIntention: string;
            /** @example 10-15K */
            expectedSalary: string;
            workHistory: components["schemas"]["ResumeWorkHistory"][];
            /** @example 2026-02-03T10:00:00.000Z */
            extractedAt: string;
            /** @example R123456 */
            resumeId?: string;
            /** @example U987654 */
            perUserId?: string;
        };
        ResumesResponse: {
            /** @enum {boolean} */
            success: true;
            sample?: components["schemas"]["ResumeSample"];
            metadata?: components["schemas"]["ResumeMetadata"];
            summary?: {
                total: number;
                returned: number;
                query?: string;
            };
            data: components["schemas"]["ResumeItem"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
