/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health check
         * @description Returns the health status of the API
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Service is healthy */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HealthResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trends": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get trending news
         * @description Returns the latest trending news items from various platforms
         */
        get: {
            parameters: {
                query?: {
                    platform?: string;
                    date?: string;
                    limit?: string;
                    include_url?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successful response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TrendsResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trends/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get trend details
         * @description Returns detailed information about a specific trend item
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successful response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TrendDetailResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/topics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get trending topics
         * @description Returns aggregated trending topics based on keyword frequency
         */
        get: {
            parameters: {
                query?: {
                    top_n?: string;
                    mode?: "daily" | "current";
                    extract_mode?: "keywords" | "auto_extract";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successful response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TopicsResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search news
         * @description Search news items by keyword across platforms and dates
         */
        get: {
            parameters: {
                query: {
                    q: string;
                    platform?: string;
                    start_date?: string;
                    end_date?: string;
                    limit?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Search results */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SearchResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rss": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get RSS feed items
         * @description Returns the latest RSS feed items
         */
        get: {
            parameters: {
                query?: {
                    feed?: string;
                    days?: string;
                    limit?: string;
                    include_summary?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description RSS items */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RssResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/resumes/samples": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List resume sample files
         * @description Returns available resume sample JSON files stored under output/resumes/samples
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successful response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ResumeSamplesResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/resumes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List resumes from a sample file
         * @description Returns resume items from the latest or specified sample JSON
         */
        get: {
            parameters: {
                query?: {
                    sample?: string;
                    q?: string;
                    limit?: number;
                    offset?: string;
                    sessionId?: string;
                    jobDescriptionId?: string;
                    minMatchScore?: string;
                    sortBy?: "score" | "name" | "experience" | "extractedAt";
                    sortOrder?: "asc" | "desc";
                    minExperience?: string;
                    maxExperience?: string;
                    education?: string[];
                    skills?: string[];
                    locations?: string[];
                    minSalary?: string;
                    maxSalary?: string;
                    recommendation?: string[];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successful response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ResumesResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/resumes/match": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Match resumes with a job description
         * @description Runs AI matching and stores results for the session
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["MatchRequest"];
                };
            };
            responses: {
                /** @description Matching results */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MatchResponse"];
                    };
                };
                /** @description Session or job description not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {boolean} */
                            success: false;
                            error: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/resumes/matches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get cached resume matches
         * @description Returns cached match results for a session or job description
         */
        get: {
            parameters: {
                query?: {
                    sessionId?: string;
                    jobDescriptionId?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Match results */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ResumeMatchesResponse"];
                    };
                };
                /** @description Missing query parameters */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {boolean} */
                            success: false;
                            error: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/industry/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get industry data statistics
         * @description Returns counts of companies, keywords, and brands loaded from config
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Statistics about loaded industry data */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {boolean} */
                            success: true;
                            stats: {
                                loadedAt: string;
                                companiesCount: number;
                                keywordsCount: number;
                                brandsCount: number;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/industry/companies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all companies
         * @description Returns all companies from industry data (key companies, ITES exhibitors, agents)
         */
        get: {
            parameters: {
                query?: {
                    category?: "key_company" | "ites_exhibitor" | "agent";
                    q?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of companies */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {boolean} */
                            success: true;
                            count: number;
                            data: {
                                id: number;
                                nameCn: string;
                                nameEn?: string;
                                type: string;
                                /** @enum {string} */
                                category: "key_company" | "ites_exhibitor" | "agent";
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/industry/keywords": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all keywords
         * @description Returns all technical keywords organized by category
         */
        get: {
            parameters: {
                query?: {
                    category?: "machining" | "lathe" | "edm" | "measurement" | "smt" | "3d_printing";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of keywords */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {boolean} */
                            success: true;
                            count: number;
                            data: {
                                id: number;
                                keyword: string;
                                english?: string;
                                /** @enum {string} */
                                category: "machining" | "lathe" | "edm" | "measurement" | "smt" | "3d_printing";
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/industry/brands": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all brands
         * @description Returns all equipment brands (international, domestic, agents)
         */
        get: {
            parameters: {
                query?: {
                    origin?: "international" | "domestic" | "agent";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of brands */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {boolean} */
                            success: true;
                            count: number;
                            data: {
                                id: number;
                                nameCn: string;
                                nameEn?: string;
                                type: string;
                                /** @enum {string} */
                                origin: "international" | "domestic" | "agent";
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/industry/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Verify a company, keyword, or brand
         * @description Check if a value matches known industry data and returns confidence score
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @enum {string} */
                        type: "company" | "keyword" | "brand";
                        value: string;
                        category?: string;
                    };
                };
            };
            responses: {
                /** @description Verification result with confidence and matches */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {boolean} */
                            success: true;
                            result: {
                                verified: boolean;
                                confidence: number;
                                match?: unknown;
                                matches?: unknown[];
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/industry/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Validate markdown format
         * @description Check the industry data markdown file for format issues
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Validation results with any issues found */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {boolean} */
                            success: true;
                            valid: boolean;
                            issues: {
                                section: string;
                                row: number;
                                issue: string;
                                /** @enum {string} */
                                severity: "error" | "warning";
                            }[];
                            stats: {
                                totalTables: number;
                                totalRows: number;
                                tablesWithIssues: number;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/industry/reload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reload industry data
         * @description Clear cache and reload data from config files
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description New statistics after reload */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {boolean} */
                            success: true;
                            stats: {
                                loadedAt: string;
                                companiesCount: number;
                                keywordsCount: number;
                                brandsCount: number;
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/job-descriptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List job description files
         * @description Returns Markdown job descriptions with auto_match config
         */
        get: {
            parameters: {
                query?: {
                    includeReadme?: boolean | null;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of job descriptions */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {boolean} */
                            success: true;
                            items: {
                                id: string;
                                name: string;
                                filename: string;
                                updatedAt: string;
                                size: number;
                                title?: string;
                                titleEn?: string;
                                status?: string;
                                location?: string;
                                autoMatch?: {
                                    keywords: string[];
                                    locations: string[];
                                    priority: number;
                                    filter_preset?: string;
                                };
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/job-descriptions/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Job description statistics */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Statistics */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {boolean} */
                            success: true;
                            stats: {
                                total: number;
                                active: number;
                                withAutoMatch: number;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/job-descriptions/match": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Auto-match JD from keywords
         * @description Find the best matching job description based on input keywords
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        keywords: string[];
                        location?: string;
                    };
                };
            };
            responses: {
                /** @description Match result */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {boolean} */
                            success: true;
                            matched?: string;
                            title?: string;
                            confidence: number;
                            matchedKeywords: string[];
                            filterPreset?: string;
                            suggestedFilters?: {
                                [key: string]: unknown;
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/job-descriptions/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get job description content */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    name: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Job description content */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {boolean} */
                            success: true;
                            item: {
                                id: string;
                                name: string;
                                filename: string;
                                updatedAt: string;
                                size: number;
                                title?: string;
                                titleEn?: string;
                                status?: string;
                                location?: string;
                                autoMatch?: {
                                    keywords: string[];
                                    locations: string[];
                                    priority: number;
                                    filter_preset?: string;
                                };
                            };
                            content: string;
                        };
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a new search session */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        userId?: string;
                        jobDescriptionId?: string;
                        sampleName?: string;
                        filters?: components["schemas"]["ResumeFilters"];
                    };
                };
            };
            responses: {
                /** @description Session created */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {boolean} */
                            success: true;
                            session: {
                                /** @example session-123 */
                                id: string;
                                /** @example user-1 */
                                userId?: string;
                                /** @example lathe-sales */
                                jobDescriptionId?: string;
                                /** @example sample-initial */
                                sampleName?: string;
                                filters?: components["schemas"]["ResumeFilters"];
                                /**
                                 * @example active
                                 * @enum {string}
                                 */
                                status: "active" | "completed" | "archived";
                                /** @example 2026-02-05T08:00:00.000Z */
                                createdAt: string;
                                /** @example 2026-02-05T08:00:00.000Z */
                                updatedAt: string;
                                /** @example 2026-02-10T08:00:00.000Z */
                                expiresAt?: string;
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a search session */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Session details */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {boolean} */
                            success: true;
                            session: {
                                /** @example session-123 */
                                id: string;
                                /** @example user-1 */
                                userId?: string;
                                /** @example lathe-sales */
                                jobDescriptionId?: string;
                                /** @example sample-initial */
                                sampleName?: string;
                                filters?: components["schemas"]["ResumeFilters"];
                                /**
                                 * @example active
                                 * @enum {string}
                                 */
                                status: "active" | "completed" | "archived";
                                /** @example 2026-02-05T08:00:00.000Z */
                                createdAt: string;
                                /** @example 2026-02-05T08:00:00.000Z */
                                updatedAt: string;
                                /** @example 2026-02-10T08:00:00.000Z */
                                expiresAt?: string;
                            };
                        };
                    };
                };
                /** @description Session not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update a search session */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        userId?: string;
                        jobDescriptionId?: string;
                        sampleName?: string;
                        filters?: components["schemas"]["ResumeFilters"];
                        /** @enum {string} */
                        status?: "active" | "completed" | "archived";
                        expiresAt?: string;
                    };
                };
            };
            responses: {
                /** @description Session updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {boolean} */
                            success: true;
                            session: {
                                /** @example session-123 */
                                id: string;
                                /** @example user-1 */
                                userId?: string;
                                /** @example lathe-sales */
                                jobDescriptionId?: string;
                                /** @example sample-initial */
                                sampleName?: string;
                                filters?: components["schemas"]["ResumeFilters"];
                                /**
                                 * @example active
                                 * @enum {string}
                                 */
                                status: "active" | "completed" | "archived";
                                /** @example 2026-02-05T08:00:00.000Z */
                                createdAt: string;
                                /** @example 2026-02-05T08:00:00.000Z */
                                updatedAt: string;
                                /** @example 2026-02-10T08:00:00.000Z */
                                expiresAt?: string;
                            };
                        };
                    };
                };
                /** @description Session not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/api/actions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List actions for a session */
        get: {
            parameters: {
                query: {
                    sessionId: string;
                    latestOnly?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Action list */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {boolean} */
                            success: true;
                            actions: {
                                id: number;
                                userId?: string;
                                sessionId?: string;
                                resumeId: string;
                                /** @enum {string} */
                                actionType: "star" | "shortlist" | "reject" | "archive" | "note" | "contact";
                                actionData?: {
                                    [key: string]: unknown;
                                };
                                createdAt: string;
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        /** Create a candidate action */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        userId?: string;
                        sessionId?: string;
                        resumeId: string;
                        /** @enum {string} */
                        actionType: "star" | "shortlist" | "reject" | "archive" | "note" | "contact";
                        actionData?: {
                            [key: string]: unknown;
                        };
                    };
                };
            };
            responses: {
                /** @description Action created */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {boolean} */
                            success: true;
                            action: {
                                id: number;
                                userId?: string;
                                sessionId?: string;
                                resumeId: string;
                                /** @enum {string} */
                                actionType: "star" | "shortlist" | "reject" | "archive" | "note" | "contact";
                                actionData?: {
                                    [key: string]: unknown;
                                };
                                createdAt: string;
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search-profiles/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search profiles statistics */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Profile statistics */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {boolean} */
                            success: true;
                            stats: {
                                total: number;
                                active: number;
                                paused: number;
                                archived: number;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search-profiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all search profiles */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of search profiles */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {boolean} */
                            success: true;
                            profiles: {
                                id: string;
                                name: string;
                                filename: string;
                                updatedAt: string;
                                /** @enum {string} */
                                status: "active" | "paused" | "archived";
                                location: string;
                                keywords: string[];
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search-profiles/:id": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get search profile by ID */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Profile details */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {boolean} */
                            success: true;
                            profile: {
                                [key: string]: unknown;
                            };
                        };
                    };
                };
                /** @description Profile not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {boolean} */
                            success: false;
                            error: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search-profiles/auto-match": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Auto-match profile from keywords
         * @description Find the best matching search profile based on input keywords and location
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        keywords: string[];
                        location?: string;
                    };
                };
            };
            responses: {
                /** @description Match result */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {boolean} */
                            success: true;
                            profileId?: string;
                            jobDescription?: string;
                            filterPreset?: string;
                            confidence: number;
                            matchedKeywords: string[];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search-profiles/reload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Clear cache and reload profiles */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Cache cleared */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {boolean} */
                            success: true;
                            message: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/filter-presets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List filter presets */
        get: {
            parameters: {
                query?: {
                    category?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of presets */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {boolean} */
                            success: true;
                            presets: {
                                id: string;
                                name: string;
                                category: string;
                                filters: {
                                    minExperience?: number;
                                    maxExperience?: number | null;
                                    education?: string[];
                                    salaryRange?: {
                                        min?: number;
                                        max?: number;
                                    };
                                };
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/filter-presets/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List preset categories */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of categories */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {boolean} */
                            success: true;
                            categories: {
                                id: string;
                                name: string;
                                icon?: string;
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/filter-presets/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Preset statistics */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Statistics */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {boolean} */
                            success: true;
                            stats: {
                                total: number;
                                byCategory: {
                                    [key: string]: number;
                                };
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/filter-presets/:id": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get preset by ID */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Preset details */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {boolean} */
                            success: true;
                            preset: {
                                id: string;
                                name: string;
                                category: string;
                                filters: {
                                    minExperience?: number;
                                    maxExperience?: number | null;
                                    education?: string[];
                                    salaryRange?: {
                                        min?: number;
                                        max?: number;
                                    };
                                };
                            };
                        };
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthResponse: {
            /**
             * @example healthy
             * @enum {string}
             */
            status: "healthy" | "degraded" | "unhealthy";
            /** @example 2025-01-27T10:00:00Z */
            timestamp: string;
            /** @example 0.1.0 */
            version?: string;
        };
        TrendItem: {
            /** @example OpenAI announces GPT-5 */
            title: string;
            /** @example zhihu */
            platform: string;
            /** @example Zhihu Hot List */
            platform_name: string;
            /** @example 1 */
            rank: number;
            /** @example 2.5 */
            avg_rank?: number;
            /** @example 5 */
            count?: number;
            timestamp?: string;
            date?: string;
            url?: string;
            mobileUrl?: string;
        };
        TrendsResponse: {
            /** @enum {boolean} */
            success: true;
            summary?: {
                description: string;
                total: number;
                returned: number;
                platforms: string | string[];
            };
            data: components["schemas"]["TrendItem"][];
        };
        TrendDetailResponse: {
            /** @enum {boolean} */
            success: true;
            data: components["schemas"]["TrendItem"];
        };
        Topic: {
            /** @example AI */
            keyword: string;
            /** @example 15 */
            frequency: number;
            matched_news?: number;
            /** @enum {string} */
            trend?: "rising" | "stable" | "falling";
            weight_score?: number;
        };
        TopicsResponse: {
            /** @enum {boolean} */
            success: true;
            topics: components["schemas"]["Topic"][];
            generated_at?: string;
            mode?: string;
            extract_mode?: string;
            total_keywords?: number;
            description?: string;
        };
        SearchResult: {
            title: string;
            platform: string;
            platform_name: string;
            ranks?: number[];
            count?: number;
            avg_rank?: number;
            url?: string;
            mobileUrl?: string;
            date?: string;
        };
        SearchResponse: {
            /** @enum {boolean} */
            success: true;
            results: components["schemas"]["SearchResult"][];
            total: number;
            total_found?: number;
            statistics?: {
                platform_distribution?: {
                    [key: string]: number;
                };
                avg_rank?: number;
                keyword: string;
            };
        };
        RssItem: {
            title: string;
            feed_id: string;
            feed_name: string;
            url?: string;
            published_at?: string;
            author?: string;
            date?: string;
            fetch_time?: string;
            summary?: string;
        };
        RssResponse: {
            /** @enum {boolean} */
            success: true;
            summary?: {
                description: string;
                total: number;
                returned: number;
                days: number;
                feeds: string | string[];
            };
            data: components["schemas"]["RssItem"][];
        };
        ResumeSample: {
            /** @example sample-initial */
            name: string;
            /** @example sample-initial.json */
            filename: string;
            /** @example 2026-02-03T10:00:00.000Z */
            updatedAt: string;
            /** @example 10240 */
            size: number;
        };
        ResumeSamplesResponse: {
            /** @enum {boolean} */
            success: true;
            samples: components["schemas"]["ResumeSample"][];
        };
        ResumeSearchCriteria: {
            /** @example 销售 */
            keyword?: string;
            /** @example 东莞 */
            location?: string;
            /**
             * @example {
             *       "status": "active"
             *     }
             */
            filters?: {
                [key: string]: string;
            };
        };
        ResumeMetadata: {
            /** @example https://hr.job5156.com/search?keyword=销售 */
            sourceUrl?: string;
            searchCriteria?: components["schemas"]["ResumeSearchCriteria"];
            /** @example 2026-02-03T09:27:52.152Z */
            generatedAt?: string;
            /** @example browser-extension@1.0.0 */
            generatedBy?: string;
            /** @example 1 */
            totalPages?: number;
            /** @example 20 */
            totalResumes?: number;
            /** @example Navigate to sourceUrl, then add ?tr_auto_export=json */
            reproduction?: string;
        };
        ResumeWorkHistory: {
            /** @example 2021-03 ~ 2023-08 Example Co. - Sales Manager */
            raw: string;
        };
        ResumeItem: {
            /** @example Alex Chen */
            name: string;
            /** @example https://hr.job5156.com/resume/123 */
            profileUrl: string;
            /** @example Active today */
            activityStatus: string;
            /** @example 28 */
            age: string;
            /** @example 5 years */
            experience: string;
            /** @example Bachelor */
            education: string;
            /** @example Shenzhen */
            location: string;
            /** @example 认真敬业，具备团队协作精神 */
            selfIntro: string;
            /** @example Sales Manager */
            jobIntention: string;
            /** @example 10-15K */
            expectedSalary: string;
            workHistory: components["schemas"]["ResumeWorkHistory"][];
            /** @example 2026-02-03T10:00:00.000Z */
            extractedAt: string;
            /** @example R123456 */
            resumeId?: string;
            /** @example U987654 */
            perUserId?: string;
        };
        ResumesResponse: {
            /** @enum {boolean} */
            success: true;
            sample?: components["schemas"]["ResumeSample"];
            metadata?: components["schemas"]["ResumeMetadata"];
            summary?: {
                total: number;
                returned: number;
                query?: string;
            };
            data: components["schemas"]["ResumeItem"][];
        };
        ResumeMatch: {
            /** @example R123456 */
            resumeId: string;
            /** @example lathe-sales */
            jobDescriptionId: string;
            /** @example 85 */
            score: number;
            /**
             * @example ai
             * @enum {string}
             */
            scoreSource?: "rule" | "ai";
            /**
             * @example match
             * @enum {string}
             */
            recommendation: "strong_match" | "match" | "potential" | "no_match";
            /**
             * @example [
             *       "客户开发经验丰富"
             *     ]
             */
            highlights: string[];
            /**
             * @example [
             *       "缺少机床销售经验"
             *     ]
             */
            concerns: string[];
            /** @example 候选人与岗位匹配良好，可安排面试。 */
            summary: string;
            /**
             * @example {
             *       "skillMatch": 18,
             *       "experienceMatch": 25
             *     }
             */
            breakdown?: {
                [key: string]: number;
            };
            /** @example 2026-02-05T08:00:00.000Z */
            matchedAt: string;
            /** @example session-123 */
            sessionId?: string;
            /** @example user-abc */
            userId?: string;
        };
        MatchStats: {
            processed: number;
            matched: number;
            avgScore: number;
            processingTimeMs?: number;
        };
        MatchResponse: {
            /** @enum {boolean} */
            success: true;
            results: components["schemas"]["ResumeMatch"][];
            stats: components["schemas"]["MatchStats"];
        };
        MatchRequest: {
            /** @example session-123 */
            sessionId?: string;
            /** @example sample-initial */
            sample?: string;
            /** @example lathe-sales */
            jobDescriptionId: string;
            /**
             * @example [
             *       "R123456"
             *     ]
             */
            resumeIds?: string[];
            /** @example 50 */
            limit?: number;
            /**
             * @example hybrid
             * @enum {string}
             */
            mode?: "rules_only" | "hybrid" | "ai_only";
        };
        ResumeMatchesResponse: {
            /** @enum {boolean} */
            success: true;
            results: components["schemas"]["ResumeMatch"][];
        };
        ResumeFilters: {
            minExperience?: number;
            maxExperience?: number;
            education?: string[];
            skills?: string[];
            locations?: string[];
            minSalary?: number;
            maxSalary?: number;
            minMatchScore?: number;
            recommendation?: string[];
            /** @enum {string} */
            sortBy?: "score" | "name" | "experience" | "extractedAt";
            /** @enum {string} */
            sortOrder?: "asc" | "desc";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
