// Generated by openapi-typescript (placeholder). Run `npm run gen:api` to refresh.

export type ResumeWorkHistory = {
  raw: string
}

export type ResumeItem = {
  name: string
  profileUrl: string
  activityStatus: string
  age: string
  experience: string
  education: string
  location: string
  jobIntention: string
  expectedSalary: string
  workHistory: ResumeWorkHistory[]
  extractedAt: string
  resumeId?: string
  perUserId?: string
}

export type ResumeSample = {
  name: string
  filename: string
  updatedAt: string
  size: number
}

export type ResumesResponse = {
  success: true
  sample?: ResumeSample
  summary?: {
    total: number
    returned: number
    query?: string
  }
  data: ResumeItem[]
}

export type ResumeSamplesResponse = {
  success: true
  samples: ResumeSample[]
}

export type components = {
  schemas: {
    ResumeWorkHistory: ResumeWorkHistory
    ResumeItem: ResumeItem
    ResumeSample: ResumeSample
    ResumesResponse: ResumesResponse
    ResumeSamplesResponse: ResumeSamplesResponse
  }
}

export type paths = {
  "/api/resumes": {
    get: {
      parameters: {
        query?: {
          sample?: string
          q?: string
          limit?: number
        }
      }
      responses: {
        200: {
          content: {
            "application/json": components["schemas"]["ResumesResponse"]
          }
        }
      }
    }
  }
  "/api/resumes/samples": {
    get: {
      responses: {
        200: {
          content: {
            "application/json": components["schemas"]["ResumeSamplesResponse"]
          }
        }
      }
    }
  }
}
